### ISSUE TITLE
std::filesystem error

### ISSUE THREAD

**Issue by MicrocosmeStudio** [pkurth/D3D12Renderer#2]
Hi,

Thanks for sharing your work, this look very nice.
Unfortunately i am not able to successfully build the solution.

I generate the solution for VS2022.
i get this error when building it.

- D3D12Renderer\src\meta\generate_sounds.cpp(21,39): error C2664: 'std::basic_ifstream<char,std::char_traits<char>>::basic_ifstream(const char *,std::ios_base::openmode,int)' : impossible de convertir l'argument 1 de 'const std::filesystem::directory_entry' en 'const char *'

if i modify the code to pass a std::filesystem::path as argument or any other variations ::string and /or c_str() etc...
i get a lot of this errors for various cpp files.

- D3D12Renderer\src\core\hash.h(95,2): error C2766: spécialisation explicite ; 'std::hash<std::filesystem::path>' a déjà été défini (compilation du fichier source src\audio\sound.cpp)
- C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\filesystem(4342): message : voir la définition précédente de 'hash<std::filesystem::path>' (compilation du fichier source src\audio\sound.cpp)

Thx

**Comment by pkurth** [comment]
Hi,
thanks for your message. Could you pull the latest version and try again please?
Please remember to regenerate the solution with the batch script.
-Philipp

**Comment by MicrocosmeStudio** [comment]
Hi,
Thanks the solution compile fine now.
Sadly the programme does not success to fully open because some assets are not found.

![assets](https://user-images.githubusercontent.com/103967371/172027889-1bce69ee-2237-4581-9b6f-a77dc98878be.jpg)

Do you have the corresponding assets on one other depo ?

In absolute, It could be ideal to be able to open the programme on an empty scene or very basic one with minimalist environment.
