### ISSUE TITLE
ambiguous type for bit shift; use a type suffix on literal values, like 'L' or 'U', or a cast

### ISSUE THREAD

**Issue by OwlTheSheep** [pkurth/D3D12Renderer#4]
i have an issue when running the program both at release and debug mode (these 2 errors pops up):
ambiguous type for bit shift; use a type suffix on literal values, like 'L' or 'U', or a cast [-Werror,-Wambig-lit-shift] -> line 39 at bitonic_start_sort_cs.hlsl
ambiguous type for bit shift; use a type suffix on literal values, like 'L' or 'U', or a cast [-Werror,-Wambig-lit-shift] -> line 53 at bitonic_start_sort_cs.hlsl

**Comment by pkurth** [comment]
Strange, I have not had this problem. Can you paste the output of the generate script here please? 
Thanks for your message
\- Philipp

**Comment by OwlTheSheep** [comment]
hey, I tried using the fix in the issue #3 and that was the result, when downloading the repository, it didn't download the libraries in the ext/ folder which then gave me an error while cmaking the file, so I had to manually download it from github and extract them into the ext/ folder. i might have downloaded the wrong versions of those libraries that doesn't work with this project.

**Comment by pkurth** [comment]
Hi, 
Now I am confused. How is this issue related to issue #3?
What do you mean when you say "download"? Did you download a zip of the repository or did you clone it via git? You should definitely do the latter and clone recursively with submodules. 
I will try to record a video with build instructions in the near future and include the video link in the readme. Maybe this helps. 
Best regards
Philipp

**Comment by OwlTheSheep** [comment]
Hey, sorry for answering so late
When I download the file, I download it with the "Open with Github Desktop" button.
I am pretty new to github, so I sometimes get a bit confused.

I filmed a video of me using cmake for it and compiling it in both Release and Debug mode (64x bit) so try seeing what I'm doing wrong: https://www.youtube.com/watch?v=VmDJIQUg7Z8

**Comment by OwlTheSheep** [comment]
Is there maybe an already pre-compiled version you are willing to share?

**Comment by 2latemc** [comment]
Got the same issue.

**Comment by pkurth** [comment]
Sorry for the late reply, I was busy working on other things. I think I fixed the compile errors as of commit a70aa5f.
Seems like the newest Windows SDK (which I didn't have, but you did), changed some stuff, which caused these errors/warnings.

Thanks for posting the issue and recording a video. I would appreciate feedback, whether the fix worked for you.

**Comment by pkurth** [comment]
> Is there maybe an already pre-compiled version you are willing to share?

I don't think this would be very helpful. I would much rather like the project to compile without issues everywhere. Thank you very much for opening the issue, so that I can fix the compile errors.
