### ISSUE TITLE
Build error vs2022

### ISSUE THREAD

**Issue by Adrian-Nonn** [pkurth/D3D12Renderer#5]
When I try to get an weird error:

D3D12Renderer\shaders\rs\proc_placement_rs.hlsli(16,2-26): error X3000: unrecognized identifier 'uint64_t'

Any idea how to fix that?

**Comment by pkurth** [comment]
Thank you very much for finding this and pointing it out. Could you pull the newest changes and try again please?

**Comment by Adrian-Nonn** [comment]
I tried again and it works now.
