### ISSUE TITLE
Debug Error: abort() has been called

### ISSUE THREAD

**Issue by PsychoCoffee** [pkurth/D3D12Renderer#6]
When building the newest released solution, both in release and debug mode, the next error pops up:

![image](https://user-images.githubusercontent.com/89361918/222455619-d4a9c334-93bb-4e17-ad88-513f9321414a.png)

**Comment by pkurth** [comment]
I will need some more info. Can you start the program in the debugger (F5) and when the crash happens, click "Retry" in the popup from your screenshot. Visual Studio should then stop where the crash happens. 
Please then attach a screenshot of the call stack to this thread.

Thanks!

**Comment by PsychoCoffee** [comment]
Hey! Sorry for not mentioning that in the original comment.
The issue seems to be fixed with the newest release.
Thank you!
